services:
  web:
    image: kmthach/nest_microservices-auth:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - user_db
  user_db:
    image: mysql
    ports:
      - "1234:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
volumes:
  db_data: